### ISSUE TITLE
update documentation to talk about low_level_debug=1 instead of debug=1 in config.ini

### ISSUE THREAD

**Issue by maximd** [shotgunsoftware/tk-framework-desktopserver#12]
Hi,

AFAIK, the variable that should be used to enable debug in `config.ini` is now `low_level_debug=1`, not `debug=1` anymore since commit https://github.com/shotgunsoftware/tk-framework-desktopserver/commit/b7b2936bba261371e8c21b1209ca54e99e0d745b

Though the documentation still mentions it [tk-framework-desktopserver - Documentation - Security Setup - Local Shotgun Installs](https://github.com/shotgunsoftware/tk-framework-desktopserver/wiki/Documentation#security-setup---local-shotgun-installs)

In fact after searching more, I stumbled upon the [Desktop Startup Framework release notes for v1.3.19](https://support.shotgunsoftware.com/entries/97454918#v1.3.19) which *does* mention the change of name and points to this [config.ini.exemple](https://github.com/shotgunsoftware/tk-framework-desktopstartup/blob/5f52a961e8e1e8c95a765ee08d766d7ea289d571/config.ini.example#L48-L53).

So maybe it would just be more clear if [tk-framework-desktopserver - Documentation - Security Setup - Local Shotgun Installs](https://github.com/shotgunsoftware/tk-framework-desktopserver/wiki/Documentation#security-setup---local-shotgun-installs) could be updated to use `low_level_debug=1` and gives a link to the `config.ini.exemple` file

Best,
Maxim

**Comment by jfboismenu** [comment]
Hi Maxim!
Thanks for bringing this to our attention. We've just fixed the documentation.
Have a nice day!
JF
